jobs:
  build_and_test:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      - run: sudo apt-get update

      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: clang clang-tidy clang-format
          version: 1.0

      - run: make lint
      - run: make clean clang-tidy
      - run: make clean clang-everything

on:
  push:
  pull_request:
  workflow_dispatch:
